(defun kdisneur-keybindings/define-all-bindings (definitions)
  (dolist (definition definitions)
    (let ((mode (car definition))
          (bindings (cdr definition)))
      (if (equal mode ':global)
          (kdisneur-keybindings/define-global-binding bindings)
        (kdisneur-keybindings/define-mode-binding mode bindings)))))

(defun kdisneur-keybindings/define-global-binding (bindings)
  (dolist (binding bindings)
    (let ((shortcut (car binding))
          (title (car (cdr binding)))
          (command (car (cdr (cdr binding)))))
      (bind-key shortcut command)
      (which-key-add-key-based-replacements shortcut title))))

(defun kdisneur-keybindings/define-mode-binding (mode bindings)
  (dolist (binding bindings)
    (let ((shortcut (car binding))
          (title (car (cdr binding)))
          (command (car (cdr (cdr binding)))))
      (bind-key shortcut command (eval (intern (concat (symbol-name mode) "-map"))))
      (which-key-add-major-mode-key-based-replacements mode shortcut title))))

(kdisneur-keybindings/define-all-bindings
 '((:global
    ("M-f" "Next start of word" forward-to-word)
    ("M-g" "Next end of word" forward-word)
    ("M-x" "Execute command" helm-M-x)
    ("C-x C-f" "Find files" helm-find-files)
    ("C-=" "Expand region" er/expand-region)
    ("C-S-a" "Back to indentation" back-to-indentation)
    ("C-o" "Append line" kdisneur-custom/create-next-line-and-goto)
    ("C-S-o" "Insert line" kdisneur-custom/create-previous-line-and-goto)
    ("C-. :" "Execute command" helm-M-x)
    ("C-. a s" "Servers" prodigy)
    ("C-. a p" "Proceses" helm-top)
    ("C-. a w" "Wikipedia" helm-wikipedia-suggest)
    ("C-. b j" "Junk file" open-junk-file)
    ("C-. b n" "Next buffer" next-buffer)
    ("C-. b p" "Previous buffer" previous-buffer)
    ("C-. e n" "Next error" flycheck-next-error)
    ("C-. e p" "Previous error" flycheck-previous-error)
    ("C-. e c" "Clear errors" flycheck-clear)
    ("C-. f c" "Find Emacs conf" kdisneur-custom/find-init-file)
    ("C-. f f" "Find files" helm-find-files)
    ("C-. f r" "Find recent files" helm-recentf)
    ("C-. f s" "Save file" save-buffer)
    ("C-. p b" "Find recent files" helm-projectile-switch-to-buffer)
    ("C-. p / /" "Search in files" helm-projectile-ag)
    ("C-. p f" "Find files" helm-projectile-find-file)
    ("C-. p p" "Switch project" helm-projectile-switch-project)
    ("C-. q q" "Quit" save-buffers-kill-emacs)
    ("C-. q r" "Restart" restart-emacs)
    ("C-. a t s" "Start a new session" multi-term)
    ("C-. a t n" "Next session" multi-term-next)
    ("C-. a t p" "Previous session" multi-term-prev))
   (alchemist-test-mode
    ("C-. j n" "Jump to next test" alchemist-test-mode-jump-to-next-test)
    ("C-. j p" "Jump to previous test" alchemist-test-mode-jump-to-previous-test))
   (alchemist-test-report-mode
    ("C-. e n" "Next error" alchemist-test-next-result)
    ("C-. e p" "Previous error" alchemist-test-previous-result))
   (elixir-mode
    ("C-. j b" "Jump back" alchemist-goto-jump-back)
    ("C-. j d" "Jump to definition" alchemist-goto-definition-at-point)
    ("C-. j n" "Jump to next function" alchemist-goto-jump-to-next-def-symbol)
    ("C-. j p" "Jump to previous function" alchemist-goto-jump-to-previous-def-symbol)
    ("C-. j t" "Jump to test" alchemist-project-toggle-file-and-tests)
    ("C-. j T" "Jummp to test other window" alchemist-project-toggle-file-and-tests-other-window)
    ("C-. t a" "Test suite" alchemist-mix-test)
    ("C-. t b" "Test buffer" alchemist-mix-test-this-buffer)
    ("C-. t r" "Run latest" alchemist-mix-rerun-last-test)
    ("C-. t t" "Test function" alchemist-mix-test-at-point))
   (emacs-lisp-mode
    ("C-. f l" "Find Lisp libraries" helm-locate-library)
    ("C-. j d" "Jump to definition" kdisneur-custom/jump-to-lisp-function)
    ("C-. j n" "Jump to next function" kdisneur-custom/jump-to-next-lisp-function)
    ("C-. j p" "Jump to previous function" kdisneur-custom/jump-to-previous-lisp-function)
    ("C-. x b" "Eval buffer" eval-buffer)
    ("C-. x f" "Eval function" eval-defun))
   (js2-mode
    ("C-. r f" "Extract to function" js2r-extract-function))
   (ruby-mode
    ("C-. j n" "Jump to next method" kdisneur-custom/jump-to-next-ruby-function)
    ("C-. j p" "Jump to previous method" kdisneur-custom/jump-to-previous-ruby-function)
    ("C-. p / c" "Search in Ruby files" kdisneur-custom/helm-projectile-ag-ruby)
    ("C-. r b" "Block syntax" ruby-toggle-block)
    ("C-. r c" "Multiline if" ruby-refactor-convert-post-conditional)
    ("C-. r h" "Hash syntax" ruby-toggle-hash-syntax)
    ("C-. r f" "Extract to method" ruby-refactor-extract-to-method)
    ("C-. s '" "Single quote" ruby-tools-to-single-quote-string)
    ("C-. s \"" "Double quote" ruby-tools-to-double-quote-string)
    ("C-. s :" "Symbol" ruby-tools-to-symbol))
   (text-mode
    ("C-. e s" "Spelling suggestion" helm-flyspell-correct)
    ("C-. e n" "Next error" flyspell-goto-next-error)
    ("C-. e p" "Previous error" flyspell-goto-previous-error))))

(provide 'kdisneur-keybindings)
