call plug#begin('~/.vim/plugged')
Plug 'kana/vim-textobj-user'

Plug 'andyl/vim-textobj-elixir'
Plug 'chaoren/vim-wordmotion'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'google/vim-jsonnet'
Plug 'jeetsukumaran/vim-buffergator'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'itchyny/vim-qfedit'
Plug 'NLKNguyen/papercolor-theme'
Plug 'ntpeters/vim-better-whitespace'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'sheerun/vim-polyglot'
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'reedes/vim-litecorrect'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'w0rp/ale'
Plug 'wellle/targets.vim'
call plug#end()

if filereadable("/usr/local/bin/python")
  let g:python_host_prog = "/usr/local/bin/python"
end

if has('python3')
  " Hide annoying warning
  silent! python3 1
endif

let mapleader="\<Space>"

if has("nvim")
  set inccommand=nosplit
endif

set backspace=indent,eol,start " allow backspace key every time
set complete=],.,b,u " autocomplete with tag, current buffer, other buffers (loaded and unloaded)
set conceallevel=0 " do not use conceal
set diffopt+=vertical
set expandtab " use the right number of spaces when pressing tab
set formatoptions-=t "prevent auto word wrapping
set history=500 "history of commands to keep in memory
set incsearch " jump to the first match as typing
set laststatus=2 " always display the status line
set nobackup
set nocursorcolumn
set nocursorline
set nohlsearch " do not highlight search results
set nomodeline " do not enable vim executable commentary in files (i.e. /* vim: set ft=ruby*/)
set noswapfile
set nowrap " do not use softwrap
set nowritebackup
set path=.,** " search from current folder and sub folders
set wildignore+=**/.git/**
set wildignore+=**/_build/**
set wildignore+=**/deps/**
set wildignore+=**/node_modules/**
set wildignore+=**/*.jpg,**/*.JPG,**/*.png,**/*.PNG,**/*.pdf,**/*.PDF
set relativenumber " display relative number
set ruler
set shiftwidth=2 " number of spaces to use on indentation
set showcmd
set spellfile=$HOME/.vim-spell-en.utf-8.add
set tabstop=2 " number of spaces used to display tabs
set textwidth=120 " max line before breaking lines
set wildmode=full

set background=light
colorscheme PaperColor
syntax enable

set splitbelow
set splitright

for settingFile in split(globpath('~/.vim/settings', '*.vim'), '\n')
  execute 'source ' . settingFile
endfor

source ~/.vim/mapping.vim

if filereadable("~/.vim/vimrc.local")
  source ~/.vim/vimrc.local
endif

function! CurrentHighlightGroups()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunction
