if has('nvim')
  let s:packages = globpath(expand('~/.vim/pack/nvimonly/opt'), '*')
else
  let s:packages = globpath(expand('~/.vim/pack/vimonly/opt'), '*')
endif

for s:package in split(s:packages, '\n')
  execute ':packadd! ' . fnamemodify(s:package, ':t')
endfor

if filereadable('/usr/local/bin/python')
  let g:python_host_prog = '/usr/local/bin/python'
end

let mapleader="\<Space>"

" Indentation
set expandtab " use the right number of spaces when pressing tab
set shiftwidth=2 " number of spaces to use on indentation
set tabstop=4 " number of spaces used to display tabs

" Search
set incsearch " jump to the first match as typing
set nohlsearch " do not highlight search results

" Place splits where I expect when using `<c-w><c-v>` and `<c-w><c-s>`
set splitbelow
set splitright

" Define how omifunc completion behave
set completeopt=longest,menuone

" Theming
set background=light
colorscheme PaperColor
syntax enable

" Shell
set shellcmdflag=-c\ -i

runtime! settings/*.vim
runtime! mapping.vim

" Ensure plugins are loaded and build help tags
packloadall
silent! helptags ALL

syn match url /\(http\|https\|ftp\):\/\/[-0-9a-zA-Z_?&=+#%\/.!':;@~]\+/ contains=@NoSpell
syn region asciidocblock start='----' end='----' contains=@NoSpell
