#!/bin/bash

chmod 600 ~/.ssh/id_*
chmod 600 ~/.gnupg/*
chmod 755 ~/.git_template/hooks/*

[[ "${SHELL}" != "/bin/zsh" ]] &&  chsh -s /bin/zsh
[[ -e ~/.bin ]] && chmod u+x ~/.bin/*
[[ -e ~/.bin.local ]] && chmod u+x ~/.bin.local/*

[[ ! -e /usr/local/bin/brew ]] && /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew bundle check --file=$(dirname $0)/../Brewfile > /dev/null || brew bundle --file=$(dirname $0)/../Brewfile

[[ ! -e ~/.config/base16-shell ]] && git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

[[ ! -e ~/.vim/autoload/plug.vim ]] && curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qa -
