#! /usr/bin/env bash

chmod 600 ~/.ssh/id_*
chmod 600 ~/.gnupg/*
chmod 755 ~/.git_template/hooks/*

[[ "${SHELL}" != "/bin/zsh" ]] &&  chsh -s /bin/zsh
[[ -e ~/.bin ]] && chmod u+x ~/.bin/*
[[ -e ~/.bin.local ]] && chmod u+x ~/.bin.local/*
