#!/usr/bin/env bash

set -o errexit

root=$(dirname $0);

sudo apt update && sudo apt upgrade --yes && sudo apt autoremove
sudo grep -v '#' ${root}/ubuntu-installed-packages.txt | grep -v '^$' | xargs sudo apt install

asdf update
asdf plugin update --all

nvim --headless "+Lazy! sync" +qa
