#!/usr/bin/env bash

set -o errexit

root=$(dirname $0);

sudo apt update && sudo apt upgrade --yes && sudo apt autoremove
sudo cat ${root}/ubuntu-installed-packages.txt| xargs sudo apt install

asdf update
asdf plugin update --all

nvim --headless "+Lazy! sync" +qa
