#!/usr/bin/env bash

set -o errexit

sudo apt update && sudo apt upgrade --yes && sudo apt autoremove

asdf update
asdf plugin update --all

nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
