(spacemacs/declare-prefix-for-mode 'enh-ruby-mode "e" "extract")
(spacemacs/set-leader-keys-for-major-mode 'enh-ruby-mode "em" 'ruby-refactor-extract-to-method)
(spacemacs/set-leader-keys-for-major-mode 'enh-ruby-mode "ec" 'ruby-refactor-extract-constant)
(spacemacs/set-leader-keys-for-major-mode 'enh-ruby-mode "ep" 'ruby-refactor-convert-post-conditional)
(spacemacs/set-leader-keys-for-major-mode 'enh-ruby-mode "ep" 'ruby-refactor-convert-post-conditional)

(spacemacs/declare-prefix-for-mode 'enh-ruby-mode "sb" "blocks")
(spacemacs/set-leader-keys-for-major-mode 'enh-ruby-mode "sbo" 'own-ruby/next-block-to-oneline)
(spacemacs/set-leader-keys-for-major-mode 'enh-ruby-mode "sbO" 'own-ruby/previous-block-to-oneline)
(spacemacs/set-leader-keys-for-major-mode 'enh-ruby-mode "sbm" 'own-ruby/oneline-to-block)
