(setq own-ruby-packages '(ruby-refactor))

(defun own-ruby/init-ruby-refactor ()
  (use-package ruby-refactor)
  (add-hook 'enh-ruby-mode-hook 'ruby-refactor-mode-launch))

(defun own-ruby/previous-block-to-oneline ()
  (interactive)
  (word-search-backward "do")
  (forward-word)
  (own-ruby/block-to-oneline))

(defun own-ruby/next-block-to-oneline ()
  (interactive)
  (word-search-forward "do")
  (own-ruby/block-to-oneline))

(defun own-ruby/block-to-oneline ()
  (backward-kill-word 1)
  (insert "{")
  (next-line)
  (join-line)
  (end-of-line)
  (insert " }")
  (word-search-forward "end")
  (kill-whole-line))

(defun own-ruby/oneline-to-block ()
  (interactive)
  (beginning-of-line)
  (search-forward "{")
  (backward-delete-char 1)
  (insert "do")
  (search-forward "|")
  (search-forward "|")
  (newline-and-indent)
  (end-of-line)
  (search-backward "}")
  (delete-char 1)
  (end-of-line)
  (newline)
  (insert "end")
  (indent-according-to-mode))
