# vim:ft=kitty

## name: Flexoki (Light)
## author: Kepano
## license: MIT
## upstream: https://raw.githubusercontent.com/kepano/flexoki/main/kitty/flexoki_light.conf
## blurb: An inky color scheme for prose and code

# The basic colors
foreground              #100f0f
background              #fffcf0
selection_foreground    #100f0f
selection_background    #cecdc3

# Cursor colors
cursor                  #100f0f
cursor_text_color       #fffcf0

# kitty window border colors
active_border_color     #D14D41
inactive_border_color   #CECDC3

# Tab bar colors
active_tab_foreground   #100F0F
active_tab_background   #CECDC3
inactive_tab_foreground #6F6E69
inactive_tab_background #E6E4D9

# The basic 16 colors
# black
color0 #100f0f
color8 #b7b5ac

# red
color1  #af3029
color9  #d14d41

# green
color2  #66800b
color10 #879a39

# yellow
color3  #ad8301
color11 #d0a215

# blue
color4  #205ea6
color12 #4385be

# magenta
color5  #a02f6f
color13 #ce5d97

# cyan
color6  #24837b
color14 #3aa99f

# white
color7  #6f6e69
color15 #cecdc3
