[env]
term = "xterm-256color"

[colors]
cursor = { cursor = "#005f87", text = "#eeeeee" }

[colors.primary]
foreground = "#171421"
background = "#eeeeee"

[colors.normal]
black = "#000000"
red = "#721c24"
green = "#155724"
yellow = "#856404"
blue = "#004085"
magenta = "#cb1ed1"
cyan = "#0c5460"
white = "#818182"

[colors.bright]
black = "#767676"
red = "#f8d7da"
green = "#d4edda"
yellow = "#fff3cd"
blue = "#cce5ff"
magenta = "#fd28ff"
cyan = "#d1ecf1"
white = "#eeeeee"
