#! /bin/sh

hasCommitID() {
  git rev-parse --abbrev-ref HEAD | grep -E '^[0-9]+-' &> /dev/null
}

issueNumber() {
  git rev-parse --abbrev-ref HEAD | sed -E 's/^([0-9]+)-.*/\1/'
}

hasNoIssueInMessage() {
  ! grep "[ch$(issueNumber)]" $1 &> /dev/null
}

if hasCommitID; then
  if hasNoIssueInMessage $1; then
    message="[ch$(issueNumber)]"
    echo "Insert issue $(issueNumber) in the commit"
    echo >> $1
    echo ${message} >> $1
  else
    echo "Issue number already present"
  fi
else
  echo "Not found any issue number to add in your commit"
fi
