#! /bin/sh

hasCommitID() {
  git rev-parse --abbrev-ref HEAD | grep -E '^CU-[0-9a-z]+-' &> /dev/null
}

issueNumber() {
  git rev-parse --abbrev-ref HEAD | sed -E 's/^(CU-[0-9a-z]+)-.*/\1/'
}

hasNoIssueInMessage() {
  ! grep "[$(issueNumber)]" $1 &> /dev/null
}

if hasCommitID; then
  if hasNoIssueInMessage $1; then
    message="[$(issueNumber)]"
    echo "Insert issue $(issueNumber) in the commit"
    echo >> $1
    echo ${message} >> $1
  else
    echo "Issue number already present"
  fi
else
  echo "Not found any issue number to add in your commit"
fi
