#! /bin/bash

echo "Check test and style"
if [[ -f mix.exs ]]; then
  if ! mix test; then
    exit 1
  fi

  if mix help | grep dogma > /dev/null; then
    mix dogma
    exit $?
  fi

  if mix help | grep credo > /dev/null; then
    mix credo --strict
    exit $?
  fi
fi

